<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\CareerTrack;
use Illuminate\Database\Seeder;

final class CareerTrackSeeder extends Seeder
{
    /**
     * 校招赛道初始数据，与 config/resume_prompt_strategies.php 中的策略模板一一对应
     */
    public function run(): void
    {
        $tracks = [
            // 技术研发
            ['name' => '后端工程', 'slug' => 'backend', 'category' => 'tech', 'icon' => 'ti-server', 'color' => '#206bc4',
             'description' => 'Java/Go/Python/C++ 等后端开发岗位，强调系统设计、性能优化、技术深度',
             'optimization_focus' => ['技术栈关键词匹配', '项目成果量化', '系统设计能力展示'],
             'recommended_templates' => ['classic', 'modern'],
             'prompt_strategy_key' => 'backend',
             'keywords' => ['微服务', '分布式', '高并发', '数据库', '缓存', '消息队列', 'API', 'RESTful', '性能优化'],
             'avoid_words' => ['参与', '协助', '了解', '简单'],
             'sort_order' => 1],
            ['name' => '前端工程', 'slug' => 'frontend', 'category' => 'tech', 'icon' => 'ti-code', 'color' => '#4263eb',
             'description' => 'Web前端/全栈前端岗位，强调组件化、工程化、用户体验',
             'optimization_focus' => ['前端技术栈关键词', '组件化/工程化实践', '性能优化成果'],
             'recommended_templates' => ['modern', 'creative'],
             'prompt_strategy_key' => 'frontend',
             'keywords' => ['React', 'Vue', 'TypeScript', 'Webpack', '组件化', '响应式', '性能优化', 'SSR', '工程化'],
             'avoid_words' => ['切图', '简单页面', '套模板'],
             'sort_order' => 2],
            ['name' => '全栈工程', 'slug' => 'fullstack', 'category' => 'tech', 'icon' => 'ti-stack-2', 'color' => '#5c7cfa',
             'description' => '前后端兼顾的全栈开发岗位，强调技术广度和独立交付能力',
             'optimization_focus' => ['全链路技术能力', '独立项目经验', '快速学习与适应'],
             'recommended_templates' => ['classic', 'modern'],
             'prompt_strategy_key' => 'fullstack',
             'keywords' => ['全栈', '前后端', '独立开发', 'MVP', 'DevOps', '云服务', '数据库设计'],
             'avoid_words' => ['只负责前端', '只负责后端'],
             'sort_order' => 3],
            ['name' => '移动端开发', 'slug' => 'mobile', 'category' => 'tech', 'icon' => 'ti-device-mobile', 'color' => '#7950f2',
             'description' => 'iOS/Android/Flutter/React Native 等移动端岗位',
             'optimization_focus' => ['移动端技术栈', 'App性能优化', '用户体验意识'],
             'recommended_templates' => ['modern', 'elegant'],
             'prompt_strategy_key' => 'mobile',
             'keywords' => ['iOS', 'Android', 'Flutter', 'React Native', 'Swift', 'Kotlin', 'App', '性能优化', 'Crash'],
             'avoid_words' => ['网页', 'H5'],
             'sort_order' => 4],
            ['name' => '数据/AI', 'slug' => 'data-ai', 'category' => 'tech', 'icon' => 'ti-brain', 'color' => '#ae3ec9',
             'description' => '数据分析/算法/机器学习/NLP/CV 等AI相关岗位',
             'optimization_focus' => ['算法模型经验', '数据驱动成果', '论文/竞赛成绩'],
             'recommended_templates' => ['classic', 'timeline'],
             'prompt_strategy_key' => 'data_ai',
             'keywords' => ['机器学习', '深度学习', 'NLP', '计算机视觉', 'PyTorch', 'TensorFlow', '数据挖掘', '推荐系统', 'A/B测试'],
             'avoid_words' => ['调包', '简单分析'],
             'sort_order' => 5],
            ['name' => '测试质量', 'slug' => 'qa-test', 'category' => 'tech', 'icon' => 'ti-bug', 'color' => '#d6336c',
             'description' => '软件测试/质量保障/自动化测试岗位',
             'optimization_focus' => ['测试方法论', '自动化实践', '质量指标量化'],
             'recommended_templates' => ['classic', 'modern'],
             'prompt_strategy_key' => 'qa_test',
             'keywords' => ['自动化测试', '性能测试', 'Selenium', 'JMeter', 'CI/CD', '质量保障', '测试框架'],
             'avoid_words' => ['手动测试', '点点点'],
             'sort_order' => 6],
            ['name' => '运维DevOps', 'slug' => 'devops-sre', 'category' => 'tech', 'icon' => 'ti-cloud', 'color' => '#0ca678',
             'description' => '运维/SRE/DevOps/云原生岗位',
             'optimization_focus' => ['基础设施经验', '自动化运维', '稳定性与效率指标'],
             'recommended_templates' => ['classic', 'timeline'],
             'prompt_strategy_key' => 'devops_sre',
             'keywords' => ['Kubernetes', 'Docker', 'CI/CD', '监控', '自动化', '云原生', 'Linux', 'Terraform', '可用性'],
             'avoid_words' => ['手动部署', '重启解决'],
             'sort_order' => 7],
            ['name' => '网络安全', 'slug' => 'security', 'category' => 'tech', 'icon' => 'ti-shield-lock', 'color' => '#e03131',
             'description' => '安全工程师/渗透测试/安全运营岗位',
             'optimization_focus' => ['安全攻防经验', '安全体系建设', '合规与风控'],
             'recommended_templates' => ['classic', 'elegant'],
             'prompt_strategy_key' => 'security',
             'keywords' => ['渗透测试', '安全审计', 'WAF', '漏洞挖掘', '应急响应', '安全合规', 'CTF'],
             'avoid_words' => ['黑客', '入侵'],
             'sort_order' => 8],

            // 产品设计
            ['name' => '产品经理', 'slug' => 'product', 'category' => 'product_design', 'icon' => 'ti-compass', 'color' => '#f76707',
             'description' => '产品经理/商业产品/策略产品岗位，强调需求分析、数据驱动、商业思维',
             'optimization_focus' => ['产品方法论', '数据驱动决策', '商业影响力'],
             'recommended_templates' => ['modern', 'creative'],
             'prompt_strategy_key' => 'product',
             'keywords' => ['需求分析', '用户研究', '数据驱动', 'PRD', '竞品分析', 'A/B测试', 'ROI', '增长'],
             'avoid_words' => ['画原型', '写文档'],
             'sort_order' => 10],
            ['name' => '设计体验', 'slug' => 'design', 'category' => 'product_design', 'icon' => 'ti-palette', 'color' => '#e64980',
             'description' => 'UI/UX设计/交互设计/视觉设计岗位',
             'optimization_focus' => ['设计方法论', '用户体验成果', '设计系统建设'],
             'recommended_templates' => ['creative', 'elegant'],
             'prompt_strategy_key' => 'design',
             'keywords' => ['用户体验', '交互设计', '设计系统', 'Figma', '用户研究', '可用性测试', '视觉规范'],
             'avoid_words' => ['画图', '做界面'],
             'sort_order' => 11],

            // 商业运营
            ['name' => '运营增长', 'slug' => 'operations', 'category' => 'business', 'icon' => 'ti-chart-arrows', 'color' => '#2b8a3e',
             'description' => '用户运营/内容运营/增长运营岗位，强调数据驱动和增长成果',
             'optimization_focus' => ['增长指标量化', '运营方法论', '用户生命周期管理'],
             'recommended_templates' => ['modern', 'classic'],
             'prompt_strategy_key' => 'operations',
             'keywords' => ['用户增长', '留存', '转化率', 'DAU', 'MAU', 'LTV', 'CAC', '裂变', 'AARRR'],
             'avoid_words' => ['发推文', '写文案'],
             'sort_order' => 20],
            ['name' => '市场品牌', 'slug' => 'marketing', 'category' => 'business', 'icon' => 'ti-speakerphone', 'color' => '#e8590c',
             'description' => '市场营销/品牌策划/公关岗位',
             'optimization_focus' => ['品牌影响力', '营销ROI', '传播效果量化'],
             'recommended_templates' => ['modern', 'creative'],
             'prompt_strategy_key' => 'marketing',
             'keywords' => ['品牌', '营销', '传播', 'ROI', 'KOL', '内容营销', '市场调研', '竞品分析'],
             'avoid_words' => ['发广告', '做活动'],
             'sort_order' => 21],
            ['name' => '销售商务', 'slug' => 'sales', 'category' => 'business', 'icon' => 'ti-handshake', 'color' => '#c92a2a',
             'description' => '销售/商务拓展/大客户岗位，强调业绩和客户关系',
             'optimization_focus' => ['业绩量化', '客户关系管理', '商务谈判能力'],
             'recommended_templates' => ['classic', 'elegant'],
             'prompt_strategy_key' => 'sales',
             'keywords' => ['业绩', '客户', '签约', '营收', 'BD', '大客户', '渠道', '商务谈判'],
             'avoid_words' => ['打电话', '跑客户'],
             'sort_order' => 22],

            // 职能支持
            ['name' => '人力行政', 'slug' => 'hr-admin', 'category' => 'functional', 'icon' => 'ti-users', 'color' => '#5f3dc4',
             'description' => '人力资源/行政管理/组织发展岗位',
             'optimization_focus' => ['制度建设', '组织效能', '合规管理'],
             'recommended_templates' => ['classic', 'elegant'],
             'prompt_strategy_key' => 'hr_admin',
             'keywords' => ['招聘', '绩效', '培训', '组织发展', '薪酬', '员工关系', 'HRBP'],
             'avoid_words' => ['打杂', '行政事务'],
             'sort_order' => 30],
            ['name' => '财务法务', 'slug' => 'finance-legal', 'category' => 'functional', 'icon' => 'ti-scale', 'color' => '#364fc7',
             'description' => '财务/审计/法务/合规岗位',
             'optimization_focus' => ['专业资质', '合规管理', '风控成果'],
             'recommended_templates' => ['classic', 'elegant'],
             'prompt_strategy_key' => 'finance_legal',
             'keywords' => ['审计', '财务分析', '合规', '风控', 'CPA', '法律', '合同', '预算'],
             'avoid_words' => ['记账', '打官司'],
             'sort_order' => 31],

            // 行业领域
            ['name' => '供应链采购', 'slug' => 'supply-chain', 'category' => 'industry', 'icon' => 'ti-truck', 'color' => '#087f5b',
             'description' => '供应链管理/采购/物流岗位',
             'optimization_focus' => ['供应链优化', '成本控制', '效率提升'],
             'recommended_templates' => ['classic', 'timeline'],
             'prompt_strategy_key' => 'supply_chain',
             'keywords' => ['供应链', '采购', '物流', '成本优化', '供应商管理', '库存', '交付'],
             'avoid_words' => ['买东西', '发货'],
             'sort_order' => 40],
            ['name' => '制造工程', 'slug' => 'manufacturing', 'category' => 'industry', 'icon' => 'ti-building-factory', 'color' => '#5c940d',
             'description' => '制造工程/工艺/质量管理岗位',
             'optimization_focus' => ['工艺优化', '质量管控', '精益生产'],
             'recommended_templates' => ['classic', 'timeline'],
             'prompt_strategy_key' => 'manufacturing',
             'keywords' => ['精益生产', '六西格玛', '工艺优化', '质量管控', '自动化', '产线'],
             'avoid_words' => ['流水线', '打螺丝'],
             'sort_order' => 41],
            ['name' => '医疗健康', 'slug' => 'healthcare', 'category' => 'industry', 'icon' => 'ti-heartbeat', 'color' => '#e03131',
             'description' => '医疗/医药/生物科技岗位',
             'optimization_focus' => ['专业资质', '临床/研发经验', '合规意识'],
             'recommended_templates' => ['classic', 'elegant'],
             'prompt_strategy_key' => 'healthcare',
             'keywords' => ['临床', 'GMP', '药品', '医疗器械', '研发', '注册', '合规'],
             'avoid_words' => ['看病', '卖药'],
             'sort_order' => 42],
            ['name' => '教育培训', 'slug' => 'education', 'category' => 'industry', 'icon' => 'ti-school', 'color' => '#1971c2',
             'description' => '教育培训/教研/课程设计岗位',
             'optimization_focus' => ['教学成果', '课程研发', '学员反馈'],
             'recommended_templates' => ['classic', 'elegant'],
             'prompt_strategy_key' => 'education',
             'keywords' => ['课程设计', '教学', '教研', '学员', '在线教育', '培训', '知识体系'],
             'avoid_words' => ['讲课', '带班'],
             'sort_order' => 43],
            ['name' => '电商零售', 'slug' => 'ecommerce', 'category' => 'industry', 'icon' => 'ti-shopping-cart', 'color' => '#f76707',
             'description' => '电商运营/零售/新消费岗位',
             'optimization_focus' => ['GMV/转化率', '品类运营', '供应链协同'],
             'recommended_templates' => ['modern', 'creative'],
             'prompt_strategy_key' => 'ecommerce',
             'keywords' => ['GMV', '转化率', '品类', '直播', '私域', '供应链', '选品', '复购'],
             'avoid_words' => ['卖货', '上架'],
             'sort_order' => 44],
            ['name' => '传媒内容', 'slug' => 'media-content', 'category' => 'industry', 'icon' => 'ti-news', 'color' => '#ae3ec9',
             'description' => '新闻/内容创作/自媒体/短视频岗位',
             'optimization_focus' => ['内容影响力', '创作方法论', '数据增长'],
             'recommended_templates' => ['creative', 'modern'],
             'prompt_strategy_key' => 'media_content',
             'keywords' => ['内容创作', '短视频', '自媒体', '传播', '粉丝', '10w+', '选题', '脚本'],
             'avoid_words' => ['写稿', '拍视频'],
             'sort_order' => 45],
            ['name' => '政企公共', 'slug' => 'government', 'category' => 'government', 'icon' => 'ti-building-castle', 'color' => '#495057',
             'description' => '公务员/国企/事业单位/公共管理岗位',
             'optimization_focus' => ['政策理解', '公文写作', '组织协调'],
             'recommended_templates' => ['classic', 'elegant'],
             'prompt_strategy_key' => 'government',
             'keywords' => ['政策', '公文', '协调', '编制', '事业单位', '基层', '组织'],
             'avoid_words' => ['混日子', '铁饭碗'],
             'sort_order' => 50],
        ];

        foreach ($tracks as $track) {
            CareerTrack::updateOrCreate(
                ['slug' => $track['slug']],
                $track
            );
        }

        $this->command->info('校招赛道数据已初始化，共 ' . count($tracks) . ' 条。');
    }
}
