@php
    $editorConfig = [
    'optimizedJustDone' => session('optimized_just_done') === true,
    'template' => $resume->template ?? 'classic',
    'theme' => $theme ?? 'blue',
    'saveUrl' => route('user.resumes.save-modules', $resume),
    'showUrl' => route('user.resumes.show', $resume),
    'rawContentForDiff' => (string) $resume->content_raw,
    'optimizedContentForDiff' => (string) ($resume->optimized_text ?? ''),
    'streamTargetJob' => (string) ($resume->target_job ?? ''),
    'streamTargetCompany' => (string) ($resume->target_company ?? ''),
    'streamTargetJobTitle' => (string) ($resume->target_job_title ?? ''),
    'streamTargetJobDescription' => (string) ($resume->target_job_description ?? ''),
    'optimizeGoals' => is_array($resume->optimize_goals) && !empty($resume->optimize_goals) ? $resume->optimize_goals : ['authenticity', 'structure', 'language'],
    'optimizeMode' => 'balanced',
    'promptStrategyTemplate' => $resume->careerTrack?->prompt_strategy_key ?? 'general',
    'selectedJdKeywords' => [],
    'moduleScoreHistory' => [],
    'currentModuleOverallScore' => 0,
    'fontFamily' => $fontSettings['fontFamily'] ?? "'PingFang SC','Microsoft YaHei','Hiragino Sans GB','WenQuanYi Micro Hei',sans-serif",
    'fontSize' => $fontSettings['fontSize'] ?? '13.5',
    'lineHeight' => $fontSettings['lineHeight'] ?? '1.7',
    'headingFontSize' => $fontSettings['headingFontSize'] ?? '1.11',
    'headingColor' => $fontSettings['headingColor'] ?? '',
    'accentColor' => $fontSettings['accentColor'] ?? '',
    'bodyFontColor' => $fontSettings['bodyFontColor'] ?? '',
    'sectionSpacing' => $fontSettings['sectionSpacing'] ?? '18',
    'layoutProfile' => $fontSettings['layoutProfile'] ?? 'custom',
    'titleStyleVariant' => $fontSettings['titleStyleVariant'] ?? 'template',
    'leftColumnRatio' => $fontSettings['leftColumnRatio'] ?? '50',
    'resumeAtsScore' => $resume->ats_score,
    'resumeId' => $resume->id,
    'optimizeStreamUrl' => '',
    'optimizeStreamPrewarmUrl' => '',
    'optimizeStreamPrewarmEnabled' => false,
    'optimizeStreamPrewarmTtlSeconds' => (int) config('resume.editor.optimize_stream_prewarm.ttl_seconds', 900),
    'optimizePrimaryChannel' => (string) config('resume.editor.optimize_primary_channel', 'session'),
    'deepProgressivePreviewEnabled' => (bool) config('resume.editor.deep_progressive_preview.enabled', true),
    'deepProgressivePreviewTickMs' => (int) config('resume.editor.deep_progressive_preview.tick_ms', 1200),
    'optimizeSessionEnabled' => (bool) config('resume.optimize_session.enabled', true),
    'optimizeSessionCreateUrl' => route('user.resumes.optimize-sessions.create', $resume),
    'optimizeSessionHistoryUrl' => route('user.resumes.optimize-sessions.history', $resume),
    'optimizeStrategyGainUrl' => route('user.resumes.optimize-insights.strategy-gain', $resume),
    'advancedModelEnabled' => (bool) ($advancedModelEnabled ?? false),
    'priorityQueueEnabled' => (bool) ($priorityQueueEnabled ?? false),
    'planUpgradeUrl' => route('user.membership.pricing'),
    'applyOptimizedUrl' => route('user.resumes.apply-optimized', $resume),
    'atsScoreUrl' => route('user.resumes.ats-score', $resume),
    'importDocumentUrl' => route('user.resumes.import-document', $resume),
    'uploadAvatarUrl' => route('user.resumes.upload-avatar', $resume),
    'keywordExtractUrl' => route('user.resumes.keywords.extract'),
    'keywordParseJdUrl' => route('user.resumes.keywords.parse-jd'),
    'optimizeSectionUrl' => route('user.resumes.optimize-section'),
    'exportTaskCreateUrl' => route('user.resumes.export-tasks.create'),
    'exportTaskStatusUrlTemplate' => route('user.resumes.export-tasks.status', ['taskId' => '__TASK_ID__']),
    'defaultModules' => $defaultModules,
    'moduleTypes' => $moduleTypes,
    'moduleHintTitles' => config('resume.editor.module_hint_titles', []),
    'moduleExamples' => config('resume.editor.module_examples', []),
    'exportFilename' => Str::slug($resume->title) . '.pdf',
    ];
@endphp
<div id="editor-config" data-config='@json($editorConfig)' class="d-none"></div>
<script src="{{ asset('js/pages/user-resumes-editor-partials-editor-script-config.js') }}?v={{ @filemtime(public_path('js/pages/user-resumes-editor-partials-editor-script-config.js')) ?: time() }}"></script>
