<?php

declare(strict_types=1);

return [
    'version' => (string) env('RESUME_PROMPT_STRATEGY_VERSION', 'v1'),
    'gray' => [
        'enabled' => (bool) env('RESUME_PROMPT_STRATEGY_GRAY_ENABLED', false),
        'ratio' => (int) env('RESUME_PROMPT_STRATEGY_GRAY_RATIO', 0),
    ],
    'templates' => [
        'general' => [
            'title' => '通用策略',
            'category' => 'general',
            'mode_bias' => 'balanced',
            'goal_weights' => ['structure' => 1.0, 'language' => 1.0, 'highlights' => 0.9],
            'hard_constraints' => ['json_output_only', 'star_required', 'authenticity_first'],
            'style_rules' => ['professional', 'clear', 'concise'],
            'module_bias' => [],
            'risk_control' => ['no_fake_facts', 'no_unverified_numbers'],
        ],
        'fresh_graduate' => [
            'title' => '应届生求职',
            'category' => 'general',
            'mode_bias' => 'balanced',
            'goal_weights' => ['structure' => 1.0, 'skill_match' => 0.95, 'highlights' => 0.9, 'language' => 0.85],
            'hard_constraints' => ['json_output_only', 'star_required', 'authenticity_first'],
            'style_rules' => ['entry_level_friendly', 'clear', 'evidence_based'],
            'module_bias' => ['education' => 'results', 'project' => 'technical', 'experience' => 'balanced'],
            'risk_control' => ['no_fake_facts', 'suggest_metrics_when_missing', 'no_claim_without_evidence'],
        ],
        'backend' => [
            'title' => '后端工程',
            'category' => 'tech',
            'mode_bias' => 'deep',
            'goal_weights' => ['skill_match' => 1.0, 'ats_keywords' => 1.0, 'quantified' => 0.95, 'structure' => 0.8],
            'hard_constraints' => ['json_output_only', 'star_required', 'authenticity_first'],
            'style_rules' => ['technical', 'result_oriented'],
            'module_bias' => ['experience' => 'results', 'project' => 'technical'],
            'risk_control' => ['no_fake_facts', 'suggest_metrics_when_missing'],
        ],
        'frontend' => [
            'title' => '前端工程',
            'category' => 'tech',
            'mode_bias' => 'balanced',
            'goal_weights' => ['skill_match' => 1.0, 'ats_keywords' => 0.95, 'readability' => 0.85, 'highlights' => 0.8],
            'hard_constraints' => ['json_output_only', 'star_required', 'authenticity_first'],
            'style_rules' => ['technical', 'clear'],
            'module_bias' => ['project' => 'technical', 'experience' => 'balanced'],
            'risk_control' => ['no_fake_facts', 'no_unverified_numbers'],
        ],
        'fullstack' => [
            'title' => '全栈工程',
            'category' => 'tech',
            'mode_bias' => 'balanced',
            'goal_weights' => ['skill_match' => 1.0, 'structure' => 0.9, 'highlights' => 0.85, 'quantified' => 0.8],
            'hard_constraints' => ['json_output_only', 'star_required', 'authenticity_first'],
            'style_rules' => ['technical', 'result_oriented'],
            'module_bias' => ['project' => 'technical', 'experience' => 'results'],
            'risk_control' => ['no_fake_facts', 'suggest_metrics_when_missing'],
        ],
        'mobile' => [
            'title' => '移动端',
            'category' => 'tech',
            'mode_bias' => 'balanced',
            'goal_weights' => ['skill_match' => 1.0, 'highlights' => 0.9, 'quantified' => 0.8, 'readability' => 0.8],
            'hard_constraints' => ['json_output_only', 'star_required', 'authenticity_first'],
            'style_rules' => ['technical', 'professional'],
            'module_bias' => ['project' => 'technical'],
            'risk_control' => ['no_fake_facts', 'no_unverified_numbers'],
        ],
        'qa_test' => [
            'title' => '测试质量',
            'category' => 'tech',
            'mode_bias' => 'balanced',
            'goal_weights' => ['structure' => 1.0, 'quantified' => 0.9, 'language' => 0.85, 'highlights' => 0.8],
            'hard_constraints' => ['json_output_only', 'star_required', 'authenticity_first'],
            'style_rules' => ['quality_focused', 'clear'],
            'module_bias' => ['experience' => 'results', 'project' => 'balanced'],
            'risk_control' => ['no_fake_facts', 'suggest_metrics_when_missing'],
        ],
        'devops_sre' => [
            'title' => '运维DevOps',
            'category' => 'tech',
            'mode_bias' => 'deep',
            'goal_weights' => ['skill_match' => 1.0, 'quantified' => 0.95, 'structure' => 0.85, 'ats_keywords' => 0.9],
            'hard_constraints' => ['json_output_only', 'star_required', 'authenticity_first'],
            'style_rules' => ['technical', 'stability_oriented'],
            'module_bias' => ['experience' => 'results', 'project' => 'technical'],
            'risk_control' => ['no_fake_facts', 'suggest_metrics_when_missing'],
        ],
        'data_ai' => [
            'title' => '数据/AI',
            'category' => 'tech',
            'mode_bias' => 'deep',
            'goal_weights' => ['skill_match' => 1.0, 'quantified' => 0.95, 'highlights' => 0.9, 'ats_keywords' => 0.85],
            'hard_constraints' => ['json_output_only', 'star_required', 'authenticity_first'],
            'style_rules' => ['technical', 'evidence_based'],
            'module_bias' => ['project' => 'technical', 'experience' => 'results'],
            'risk_control' => ['no_fake_facts', 'no_unverified_numbers'],
        ],
        'security' => [
            'title' => '网络安全',
            'category' => 'tech',
            'mode_bias' => 'deep',
            'goal_weights' => ['skill_match' => 1.0, 'structure' => 0.9, 'quantified' => 0.85, 'ats_keywords' => 0.9],
            'hard_constraints' => ['json_output_only', 'star_required', 'authenticity_first'],
            'style_rules' => ['technical', 'risk_controlled'],
            'module_bias' => ['experience' => 'results', 'project' => 'technical'],
            'risk_control' => ['no_fake_facts', 'no_sensitive_leak'],
        ],
        'product' => [
            'title' => '产品经理',
            'category' => 'product_design',
            'mode_bias' => 'balanced',
            'goal_weights' => ['highlights' => 1.0, 'quantified' => 0.9, 'language' => 0.85, 'structure' => 0.8],
            'hard_constraints' => ['json_output_only', 'star_required', 'authenticity_first'],
            'style_rules' => ['business_impact', 'clarity'],
            'module_bias' => ['experience' => 'results'],
            'risk_control' => ['no_fake_facts', 'no_claim_without_evidence'],
        ],
        'design' => [
            'title' => '设计体验',
            'category' => 'product_design',
            'mode_bias' => 'balanced',
            'goal_weights' => ['highlights' => 1.0, 'language' => 0.9, 'structure' => 0.85, 'skill_match' => 0.8],
            'hard_constraints' => ['json_output_only', 'star_required', 'authenticity_first'],
            'style_rules' => ['user_centered', 'clear'],
            'module_bias' => ['project' => 'results'],
            'risk_control' => ['no_fake_facts', 'no_unverified_numbers'],
        ],
        'operations' => [
            'title' => '运营增长',
            'category' => 'business',
            'mode_bias' => 'balanced',
            'goal_weights' => ['highlights' => 1.0, 'quantified' => 0.95, 'language' => 0.85, 'structure' => 0.8],
            'hard_constraints' => ['json_output_only', 'star_required', 'authenticity_first'],
            'style_rules' => ['growth_oriented', 'business_impact'],
            'module_bias' => ['experience' => 'results'],
            'risk_control' => ['no_fake_facts', 'suggest_metrics_when_missing'],
        ],
        'marketing' => [
            'title' => '市场品牌',
            'category' => 'business',
            'mode_bias' => 'balanced',
            'goal_weights' => ['highlights' => 1.0, 'quantified' => 0.9, 'ats_keywords' => 0.85, 'language' => 0.85],
            'hard_constraints' => ['json_output_only', 'star_required', 'authenticity_first'],
            'style_rules' => ['brand_oriented', 'result_oriented'],
            'module_bias' => ['experience' => 'results', 'project' => 'balanced'],
            'risk_control' => ['no_fake_facts', 'no_unverified_numbers'],
        ],
        'sales' => [
            'title' => '销售商务',
            'category' => 'business',
            'mode_bias' => 'balanced',
            'goal_weights' => ['highlights' => 1.0, 'quantified' => 1.0, 'language' => 0.8, 'structure' => 0.75],
            'hard_constraints' => ['json_output_only', 'star_required', 'authenticity_first'],
            'style_rules' => ['result_oriented', 'customer_oriented'],
            'module_bias' => ['experience' => 'results'],
            'risk_control' => ['no_fake_facts', 'no_unverified_numbers'],
        ],
        'hr_admin' => [
            'title' => '人力行政',
            'category' => 'functional',
            'mode_bias' => 'balanced',
            'goal_weights' => ['structure' => 1.0, 'language' => 0.9, 'highlights' => 0.8, 'quantified' => 0.75],
            'hard_constraints' => ['json_output_only', 'star_required', 'authenticity_first'],
            'style_rules' => ['professional', 'policy_aligned'],
            'module_bias' => ['experience' => 'balanced'],
            'risk_control' => ['no_fake_facts', 'no_sensitive_leak'],
        ],
        'finance_legal' => [
            'title' => '财务法务',
            'category' => 'functional',
            'mode_bias' => 'balanced',
            'goal_weights' => ['structure' => 1.0, 'skill_match' => 0.9, 'language' => 0.9, 'quantified' => 0.8],
            'hard_constraints' => ['json_output_only', 'star_required', 'authenticity_first'],
            'style_rules' => ['compliance_first', 'accurate'],
            'module_bias' => ['experience' => 'results'],
            'risk_control' => ['no_fake_facts', 'no_sensitive_leak'],
        ],
        'supply_chain' => [
            'title' => '供应链采购',
            'category' => 'industry',
            'mode_bias' => 'balanced',
            'goal_weights' => ['structure' => 0.9, 'quantified' => 1.0, 'language' => 0.8, 'highlights' => 0.8],
            'hard_constraints' => ['json_output_only', 'star_required', 'authenticity_first'],
            'style_rules' => ['efficiency_oriented', 'result_oriented'],
            'module_bias' => ['experience' => 'results'],
            'risk_control' => ['no_fake_facts', 'suggest_metrics_when_missing'],
        ],
        'manufacturing' => [
            'title' => '制造工程',
            'category' => 'industry',
            'mode_bias' => 'balanced',
            'goal_weights' => ['skill_match' => 0.9, 'quantified' => 0.95, 'structure' => 0.85, 'language' => 0.8],
            'hard_constraints' => ['json_output_only', 'star_required', 'authenticity_first'],
            'style_rules' => ['process_oriented', 'quality_focused'],
            'module_bias' => ['experience' => 'results', 'project' => 'technical'],
            'risk_control' => ['no_fake_facts', 'no_unverified_numbers'],
        ],
        'healthcare' => [
            'title' => '医疗健康',
            'category' => 'industry',
            'mode_bias' => 'balanced',
            'goal_weights' => ['skill_match' => 0.9, 'structure' => 0.9, 'language' => 0.85, 'highlights' => 0.8],
            'hard_constraints' => ['json_output_only', 'star_required', 'authenticity_first'],
            'style_rules' => ['patient_centered', 'compliance_first'],
            'module_bias' => ['experience' => 'balanced'],
            'risk_control' => ['no_fake_facts', 'no_sensitive_leak'],
        ],
        'education' => [
            'title' => '教育培训',
            'category' => 'industry',
            'mode_bias' => 'balanced',
            'goal_weights' => ['language' => 0.9, 'highlights' => 0.9, 'structure' => 0.85, 'quantified' => 0.75],
            'hard_constraints' => ['json_output_only', 'star_required', 'authenticity_first'],
            'style_rules' => ['clarity', 'learner_oriented'],
            'module_bias' => ['experience' => 'results'],
            'risk_control' => ['no_fake_facts', 'no_unverified_numbers'],
        ],
        'ecommerce' => [
            'title' => '电商零售',
            'category' => 'industry',
            'mode_bias' => 'balanced',
            'goal_weights' => ['highlights' => 1.0, 'quantified' => 1.0, 'ats_keywords' => 0.8, 'language' => 0.8],
            'hard_constraints' => ['json_output_only', 'star_required', 'authenticity_first'],
            'style_rules' => ['growth_oriented', 'customer_oriented'],
            'module_bias' => ['experience' => 'results'],
            'risk_control' => ['no_fake_facts', 'suggest_metrics_when_missing'],
        ],
        'media_content' => [
            'title' => '传媒内容',
            'category' => 'industry',
            'mode_bias' => 'balanced',
            'goal_weights' => ['language' => 1.0, 'highlights' => 0.9, 'structure' => 0.85, 'quantified' => 0.7],
            'hard_constraints' => ['json_output_only', 'star_required', 'authenticity_first'],
            'style_rules' => ['storytelling', 'clear'],
            'module_bias' => ['project' => 'results'],
            'risk_control' => ['no_fake_facts', 'no_unverified_numbers'],
        ],
        'government' => [
            'title' => '政企公共',
            'category' => 'industry',
            'mode_bias' => 'balanced',
            'goal_weights' => ['structure' => 1.0, 'language' => 0.95, 'skill_match' => 0.85, 'highlights' => 0.75],
            'hard_constraints' => ['json_output_only', 'star_required', 'authenticity_first'],
            'style_rules' => ['compliance_first', 'formal'],
            'module_bias' => ['experience' => 'balanced'],
            'risk_control' => ['no_fake_facts', 'no_sensitive_leak'],
        ],
    ],
];
