<?php

declare(strict_types=1);

return [
    'optimize_session' => [
        'enabled' => (bool) env('RESUME_OPTIMIZE_SESSION_ENABLED', true),
        'accept_extended_signals' => (bool) env('RESUME_OPTIMIZE_SESSION_ACCEPT_EXTENDED_SIGNALS', true),
        'default_queue' => (string) env('RESUME_OPTIMIZE_SESSION_DEFAULT_QUEUE', 'default'),
        'priority_queue' => (string) env('RESUME_OPTIMIZE_SESSION_PRIORITY_QUEUE', 'default'),
        'heavy_queue' => (string) env('RESUME_OPTIMIZE_SESSION_HEAVY_QUEUE', 'optimize-heavy'),
        'warning_threshold_ms' => (int) env('RESUME_OPTIMIZE_SESSION_WARNING_THRESHOLD_MS', 45000),
        'stale_after_seconds' => (int) env('RESUME_OPTIMIZE_SESSION_STALE_AFTER_SECONDS', 300),
        'health_gate' => [
            'enabled' => (bool) env('RESUME_OPTIMIZE_SESSION_HEALTH_GATE_ENABLED', true),
            'lookback_seconds' => (int) env('RESUME_OPTIMIZE_SESSION_HEALTH_GATE_LOOKBACK_SECONDS', 300),
            'min_recent_samples' => (int) env('RESUME_OPTIMIZE_SESSION_HEALTH_GATE_MIN_RECENT_SAMPLES', 5),
            'max_queue_failures' => (int) env('RESUME_OPTIMIZE_SESSION_HEALTH_GATE_MAX_QUEUE_FAILURES', 3),
            'max_queue_failure_rate_percent' => (int) env('RESUME_OPTIMIZE_SESSION_HEALTH_GATE_MAX_QUEUE_FAILURE_RATE_PERCENT', 30),
            'max_stale_pending' => (int) env('RESUME_OPTIMIZE_SESSION_HEALTH_GATE_MAX_STALE_PENDING', 3),
            'max_consecutive_queue_failures' => (int) env('RESUME_OPTIMIZE_SESSION_HEALTH_GATE_MAX_CONSECUTIVE_QUEUE_FAILURES', 3),
        ],
        'authenticity_guard' => [
            'enabled' => (bool) env('RESUME_OPTIMIZE_AUTHENTICITY_GUARD_ENABLED', true),
            'default_goal' => (bool) env('RESUME_OPTIMIZE_AUTHENTICITY_DEFAULT_GOAL', true),
            'allow_disable' => (bool) env('RESUME_OPTIMIZE_AUTHENTICITY_ALLOW_DISABLE', false),
        ],
        'goal_conflicts' => [
            [
                'goals' => ['quantified', 'authenticity'],
                'priority' => 100,
                'rule' => '同时开启"量化成果"和"真实性增强"时，真实性优先：不得虚构数字。若原文缺少可验证数据，仅输出"待补充指标建议"。',
            ],
            [
                'goals' => ['concise', 'highlights'],
                'priority' => 80,
                'rule' => '同时开启"精简降噪"和"亮点提炼"时，先保留关键亮点，再压缩冗余表达，禁止压掉关键成果。',
            ],
            [
                'goals' => ['tailor_job', 'authenticity'],
                'priority' => 90,
                'rule' => '同时开启"岗位定制"和"真实性增强"时，仅允许重排和重写原有事实，不得补写未发生的岗位职责或项目结果。',
            ],
            [
                'goals' => ['leadership', 'authenticity'],
                'priority' => 95,
                'rule' => '同时开启"领导力展示"和"真实性增强"时，仅基于已有事实提炼管理贡献，不得编造管理职责或夸大团队规模。',
            ],
            [
                'goals' => ['career_pivot', 'authenticity'],
                'priority' => 90,
                'rule' => '同时开启"跨职能转型"和"真实性增强"时，仅重新框架化已有经验，不得添加未实际从事的职能经验或技能。',
            ],
            [
                'goals' => ['i18n_expression', 'concise'],
                'priority' => 60,
                'rule' => '同时开启"国际化表达"和"精简降噪"时，保留必要的双语术语对照，不要因精简而丢失英文行业术语。',
            ],
            [
                'goals' => ['industry_fit', 'tailor_job'],
                'priority' => 50,
                'rule' => '同时开启"行业适配"和"岗位定制"时，行业适配侧重用语风格，岗位定制侧重内容重排，两者互补不冲突。',
            ],
            [
                'goals' => ['project_impact', 'authenticity'],
                'priority' => 95,
                'rule' => '同时开启"项目影响力"和"真实性增强"时，仅基于已有事实放大项目影响描述，不得虚构项目规模或夸大影响范围。',
            ],
            [
                'goals' => ['tech_depth', 'concise'],
                'priority' => 70,
                'rule' => '同时开启"技术深度"和"精简降噪"时，保留关键技术决策理由和架构权衡描述，仅压缩实现细节。',
            ],
            [
                'goals' => ['innovation', 'authenticity'],
                'priority' => 90,
                'rule' => '同时开启"创新能力"和"真实性增强"时，仅基于已有创新事实提炼，不得编造创新成果或夸大创新影响。',
            ],
            [
                'goals' => ['data_driven', 'authenticity'],
                'priority' => 95,
                'rule' => '同时开启"数据驱动"和"真实性增强"时，仅使用原文已有数据或可合理推断的指标，不得编造具体数值。',
            ],
            [
                'goals' => ['certification', 'authenticity'],
                'priority' => 85,
                'rule' => '同时开启"资质认证"和"真实性增强"时，仅突出简历中已有的认证和资质，不得添加未持有的证书或资质。',
            ],
            [
                'goals' => ['cross_cultural', 'concise'],
                'priority' => 55,
                'rule' => '同时开启"跨文化协作"和"精简降噪"时，保留跨文化协作的关键成果描述，仅压缩过程性细节。',
            ],
        ],
        'ab' => [
            'enabled' => (bool) env('RESUME_OPTIMIZE_AB_ENABLED', false),
            'salt' => (string) env('RESUME_OPTIMIZE_AB_SALT', 'resume-optimize-v1'),
            'variants' => ['baseline', 'authenticity_first'],
            'ratio' => [
                'baseline' => (int) env('RESUME_OPTIMIZE_AB_RATIO_BASELINE', 50),
                'authenticity_first' => (int) env('RESUME_OPTIMIZE_AB_RATIO_AUTH', 50),
            ],
        ],
    ],
    'keyword_extractor' => [
        'driver' => (string) env('RESUME_KEYWORD_EXTRACTOR_DRIVER', 'simple'),
    ],
    'ai_throttle' => [
        'section_per_minute' => (int) env('RESUME_AI_THROTTLE_SECTION_PER_MINUTE', 12),
        'heavy_per_minute' => (int) env('RESUME_AI_THROTTLE_HEAVY_PER_MINUTE', 8),
        'by_ip_fallback_per_minute' => (int) env('RESUME_AI_THROTTLE_IP_FALLBACK_PER_MINUTE', 20),
    ],
    'template' => [
        'diversify_default_enabled' => (bool) env('RESUME_TEMPLATE_DIVERSIFY_DEFAULT_ENABLED', false),
        'diversify_max_per_position' => (int) env('RESUME_TEMPLATE_DIVERSIFY_MAX_PER_POSITION', 4),
    ],
    'import_parser' => [
        'llm_enabled' => (bool) env('RESUME_IMPORT_PARSER_LLM_ENABLED', true),
        'llm_min_confidence' => (float) env('RESUME_IMPORT_PARSER_LLM_MIN_CONFIDENCE', 0.45),
        'llm_min_module_count' => (int) env('RESUME_IMPORT_PARSER_LLM_MIN_MODULE_COUNT', 2),
        'education_school_suffixes' => [
            '大学',
            '学院',
            '学校',
            'University',
            'College',
            'Institute',
            'Academy',
            'School',
        ],
        'education_school_aliases' => [
            '北大' => '北京大学',
            '清华' => '清华大学',
            '复旦' => '复旦大学',
            '上交' => '上海交通大学',
            '浙大' => '浙江大学',
            '南大' => '南京大学',
            '武大' => '武汉大学',
            '中大' => '中山大学',
            '华科' => '华中科技大学',
            '北邮' => '北京邮电大学',
            '北航' => '北京航空航天大学',
        ],
        'education_major_keywords' => [
            '计算机', '软件', '数据', '人工智能', '网络', '信息', '电子', '通信', '自动化',
            '机械', '土木', '建筑', '材料', '化学', '生物', '医学', '护理', '药学',
            '法学', '法律', '经济', '金融', '会计', '统计', '数学', '物理', '英语',
            '日语', '管理', '设计', '传媒', '新闻', '心理', '教育', '公共管理',
            '工商管理', '市场营销', '专业', '工程', '科学', '技术',
            'Engineering', 'Science', 'Technology', 'Management', 'Economics',
            'Finance', 'Law', 'Design', 'Business', 'Computer', 'Data', 'Software', 'Network',
        ],
        'education_major_aliases' => [
            '计科' => '计算机科学与技术',
            '软工' => '软件工程',
            '网工' => '网络工程',
            '信安' => '信息安全',
            '电信' => '电子信息工程',
            '通信工程' => '通信工程',
            '自动化' => '自动化',
            '金工' => '金融工程',
            '国贸' => '国际经济与贸易',
            '工管' => '工商管理',
            '市营' => '市场营销',
        ],
        'education_degree_map' => [
            'phd' => '博士',
            '博士' => '博士',
            'master' => '硕士',
            '硕士' => '硕士',
            'bachelor' => '本科',
            '本科' => '本科',
            'mba' => 'MBA',
            'emba' => 'EMBA',
            '专科' => '专科',
            '大专' => '专科',
        ],
    ],
    'editor' => [
        'scroll_mode' => env('RESUME_EDITOR_SCROLL_MODE', 'natural'),
        'optimize_primary_channel' => (string) env('RESUME_EDITOR_OPTIMIZE_PRIMARY_CHANNEL', 'session'),
        'optimize_stream_prewarm' => [
            'enabled' => (bool) env('RESUME_EDITOR_OPTIMIZE_STREAM_PREWARM_ENABLED', true),
            'ttl_seconds' => (int) env('RESUME_EDITOR_OPTIMIZE_STREAM_PREWARM_TTL', 900),
        ],
        'deep_progressive_preview' => [
            'enabled' => (bool) env('RESUME_EDITOR_DEEP_PROGRESSIVE_PREVIEW_ENABLED', true),
            'tick_ms' => (int) env('RESUME_EDITOR_DEEP_PROGRESSIVE_PREVIEW_TICK_MS', 1200),
        ],
        'module_hint_titles' => [
            'personal' => '优先补齐基础身份信息',
            'objective' => '让岗位方向更明确',
            'education' => '突出学校、时间和核心亮点',
            'experience' => '强化职责与成果表达',
            'project' => '讲清项目背景与技术价值',
            'skill' => '用关键词覆盖核心能力',
            'certificate' => '补充证书与荣誉背书',
            'summary' => '用几句话概括你的竞争力',
        ],
        'module_examples' => [
            'personal' => [
                'name' => '张三',
                'phone' => '13800000000',
                'email' => 'zhangsan@example.com',
                'location' => '深圳',
            ],
            'objective' => [
                'target_job' => 'Laravel 后端开发工程师',
                'content' => '聚焦企业级后台系统、招聘平台或中后台建设，优先深圳 / 广州，期望在高并发与工程化方向持续深耕。',
            ],
            'education' => [
                'title' => '教育背景',
                'subtitle' => '华南理工大学 / 软件工程',
                'date' => '2018.09 - 2022.06',
                'location' => '广州',
                'content' => '系统学习软件工程、数据库系统、分布式架构等核心课程。',
                'items' => ['连续两年获得校级奖学金', '毕业设计聚焦招聘系统推荐算法与数据分析'],
            ],
            'experience' => [
                'title' => '工作经历',
                'subtitle' => '某科技有限公司 / PHP 开发工程师',
                'date' => '2023.03 - 至今',
                'location' => '深圳',
                'content' => '负责招聘业务后台、简历模块和 AI 能力接入，参与核心链路优化与迭代。',
                'items' => ['主导简历管理模块重构，接口平均响应时间下降 35%', '落地 Redis 缓存与队列异步处理，提升高峰期系统稳定性'],
            ],
            'project' => [
                'title' => '项目经验',
                'subtitle' => '智能招聘平台 / 后端负责人',
                'date' => '2024.01 - 2024.08',
                'location' => 'ToB SaaS',
                'content' => '负责项目后端架构设计、权限模型和简历智能处理能力建设。',
                'items' => ['设计多租户权限模型，支持 100+ 企业客户隔离接入', '完成 AI 简历优化链路接入，显著提升用户编辑效率与转化'],
            ],
            'skill' => [
                'title' => '技能特长',
                'items' => ['熟悉 Laravel、PHP 8、RESTful API 设计与服务拆分', '掌握 MySQL、Redis、消息队列与常见性能优化手段', '具备 Docker、Linux、Nginx 部署与排障经验'],
            ],
            'certificate' => [
                'title' => '荣誉证书',
                'items' => ['阿里云 ACP 认证', '全国大学生软件设计竞赛省级二等奖'],
            ],
            'summary' => [
                'title' => '自我评价',
                'content' => '5 年后端开发经验，长期参与企业级后台系统建设，熟悉 Laravel 技术栈、缓存队列和工程化协作流程，能够独立负责模块设计、性能优化与线上问题排查。',
            ],
        ],
    ],
    'observability' => [
        'alerts' => [
            'failed_rate_percent' => (float) env('RESUME_OPTIMIZE_ALERT_FAILED_RATE', 8),
            'duration_p95_ms' => (int) env('RESUME_OPTIMIZE_ALERT_DURATION_P95', 90000),
            'apply_rate_percent' => (float) env('RESUME_OPTIMIZE_ALERT_APPLY_RATE', 35),
        ],
    ],
];
